[package]
name = "win32api"
version = "0.1.0"
edition = "2021"


[dependencies]
winapi = {version="0.3.9", features=["winuser","errhandlingapi","libloaderapi","fileapi","winbase"]}
windows = {version ="0.58.0",features=[]}

